import { Shield, Lock, Brain, Users, Code2 } from "lucide-react";

const techStack = [
  { name: "Next.js 14", color: "bg-gray-900 text-white" },
  { name: "React", color: "bg-sky-100 text-sky-700" },
  { name: "Tailwind CSS", color: "bg-cyan-100 text-cyan-700" },
  { name: "FastAPI", color: "bg-emerald-100 text-emerald-700" },
  { name: "LangGraph", color: "bg-purple-100 text-purple-700" },
  { name: "Google Gemini", color: "bg-blue-100 text-blue-700" },
  { name: "Supabase", color: "bg-green-100 text-green-700" },
  { name: "TypeScript", color: "bg-indigo-100 text-indigo-700" },
  { name: "Python", color: "bg-yellow-100 text-yellow-800" },
  { name: "Recharts", color: "bg-pink-100 text-pink-700" },
];

const teamMembers = [
  { name: "Marco Ayuste", role: "Full-Stack Developer" },
  { name: "Pera Kasemsripitak", role: "Frontend Engineer" },
  { name: "Aahir Chakra", role: "UI/UX Designer" },
  { name: "Peter Lee", role: "Backend Engineer" },
];

export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-8">
      {/* Hero */}
      <div className="text-center">
        <div className="inline-flex items-center justify-center w-16 h-16 bg-emerald-100 rounded-2xl mb-4">
          <Shield className="w-8 h-8 text-emerald-600" />
        </div>
        <h1 className="text-3xl font-bold text-gray-900 mb-3">About VIGIL</h1>
        <p className="text-lg text-gray-600 max-w-xl mx-auto">
          VIGIL is a multi-agent AI system that helps university students detect healthcare
          billing fraud, discover unused insurance benefits, and make informed decisions about
          their coverage.
        </p>
      </div>

      {/* Privacy Notice */}
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
            <Lock className="w-5 h-5 text-blue-600" />
          </div>
          <h2 className="text-lg font-semibold text-gray-800">Privacy Notice</h2>
        </div>
        <p className="text-sm text-gray-600 leading-relaxed">
          VIGIL uses synthetic data for demonstration purposes. No real patient data is stored
          or processed. Receipt images uploaded during the demo are analyzed in-memory and are
          not retained after the session ends. All provider profiles, student records, and
          claims data shown in this application are entirely fictional.
        </p>
      </div>

      {/* Responsible AI */}
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center">
            <Brain className="w-5 h-5 text-purple-600" />
          </div>
          <h2 className="text-lg font-semibold text-gray-800">Responsible AI Statement</h2>
        </div>
        <p className="text-sm text-gray-600 leading-relaxed">
          Fraud flags generated by VIGIL represent potential billing anomalies identified through
          automated analysis against the Ontario Dental Association (ODA) Suggested Fee Guide.
          They are not accusations of wrongdoing. Human approval is required before any action
          is taken, and students retain full control over whether to escalate, dispute, or dismiss
          any flagged case. VIGIL is designed to empower students with information, not to replace
          professional judgement.
        </p>
      </div>

      {/* Team */}
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 bg-amber-100 rounded-lg flex items-center justify-center">
            <Users className="w-5 h-5 text-amber-600" />
          </div>
          <h2 className="text-lg font-semibold text-gray-800">Team</h2>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {teamMembers.map((member) => (
            <div key={member.name} className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
              <div className="w-10 h-10 bg-emerald-200 rounded-full flex items-center justify-center text-emerald-800 font-bold text-sm">
                {member.name.split(" ").map((n) => n[0]).join("")}
              </div>
              <div>
                <p className="text-sm font-semibold text-gray-800">{member.name}</p>
                <p className="text-xs text-gray-500">{member.role}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Tech Stack */}
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 bg-indigo-100 rounded-lg flex items-center justify-center">
            <Code2 className="w-5 h-5 text-indigo-600" />
          </div>
          <h2 className="text-lg font-semibold text-gray-800">Tech Stack</h2>
        </div>
        <div className="flex flex-wrap gap-2">
          {techStack.map((tech) => (
            <span
              key={tech.name}
              className={`text-xs font-medium px-3 py-1.5 rounded-full ${tech.color}`}
            >
              {tech.name}
            </span>
          ))}
        </div>
      </div>

      {/* Footer note */}
      <p className="text-center text-xs text-gray-400 pb-4">
        Built for GenAI Hackathon 2026 | University of Toronto
      </p>
    </div>
  );
}
